[package]
name = "wzdx-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["wzdx"]
homepage = "https://github.com/phish3y/wzdx-rs"
repository = "https://github.com/phish3y/wzdx-rs"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"

